import React, { useState, useEffect } from 'react';
import { 
  Code, Save, Play, Clipboard, Check, Trash2, Plus, Search, 
  Sparkles, CheckCircle2, AlertCircle, FileCode, Tag, Clock, Cloud, Lock
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { db } from '../firebase';
import { 
  collection, query, where, getDocs, doc, setDoc, deleteDoc, 
  serverTimestamp, onSnapshot, updateDoc 
} from 'firebase/firestore';

interface Snippet {
  id: string;
  userId: string;
  title: string;
  code: string;
  description: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

interface ScriptSandboxProps {
  sessionUser: { uid: string; displayName: string; photoURL: string; email: string } | null;
  theme: 'studio-light' | 'studio-dark' | 'neon' | 'ultradark';
  triggerToast: (msg: string) => void;
  onShowAuth: () => void;
  preloadedCode?: string;
  onClearPreloadedCode?: () => void;
}

export function ScriptSandbox({ sessionUser, theme, triggerToast, onShowAuth, preloadedCode, onClearPreloadedCode }: ScriptSandboxProps) {
  const [snippets, setSnippets] = useState<Snippet[]>([]);
  const [selectedSnippet, setSelectedSnippet] = useState<Snippet | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  // Form states for the current workspace
  const [title, setTitle] = useState('New Luau Snippet');
  const [code, setCode] = useState('-- [[ StudioHub Luau Script ]]\n-- Write your custom Roblox scripts here\n\nfunction activateHack()\n    print("Executing custom hack registers...")\nend\n\nactivateHack()');
  const [description, setDescription] = useState('My performance config script');
  const [tagInput, setTagInput] = useState('farming, mobile');

  // Linter & compilation simulator states
  const [lintResult, setLintResult] = useState<{
    status: 'idle' | 'success' | 'error';
    message: string;
    errors: string[];
  }>({ status: 'idle', message: '', errors: [] });
  const [isLinting, setIsLinting] = useState(false);
  const [copiedLoadstring, setCopiedLoadstring] = useState(false);

  const isDark = theme === 'studio-dark' || theme === 'ultradark' || theme === 'neon';

  // Listen to incoming preloaded code
  useEffect(() => {
    if (preloadedCode) {
      setCode(preloadedCode);
      setTitle('Imported AI Template');
      setDescription('Luau script generated by Sentinel-1 Support Assistant');
      if (onClearPreloadedCode) {
        onClearPreloadedCode();
      }
      triggerToast('AI Script outline loaded successfully! Click Run to compile.');
    }
  }, [preloadedCode, onClearPreloadedCode, triggerToast]);

  // Code Templates list
  const templates = [
    {
      name: 'WalkSpeed Loop',
      desc: 'Maintains WalkSpeed securely',
      code: `-- [[ SECURE WALKSPEED BUFFER ]]\nlocal targetSpeed = 120\nlocal lp = game:GetService("Players").LocalPlayer\n\nspawn(function()\n    while wait(0.5) do\n        if lp.Character and lp.Character:FindFirstChild("Humanoid") then\n            lp.Character.Humanoid.WalkSpeed = targetSpeed\n        end\n    end\nend)`
    },
    {
      name: 'Infinite Jump',
      desc: 'Bypasses jump checks',
      code: `-- [[ UNIVERSAL INFINITE JUMP ]]\nlocal UserInputService = game:GetService("UserInputService")\n\nUserInputService.JumpRequest:Connect(function()\n    local player = game.Players.LocalPlayer\n    if player and player.Character then\n        local humanoid = player.Character:FindFirstChildOfClass("Humanoid")\n        if humanoid then\n            humanoid:ChangeState("Jumping")\n        end\n    end\nend)`
    },
    {
      name: 'Custom ESP',
      desc: 'Draws vector tracer lines',
      code: `-- [[ SYSTEM GRAPHICS TRACERS ]]\nfunction createTracer(player)\n    if player == game.Players.LocalPlayer then return end\n    -- Render active bounding box lines\n    print("Attaching visual box to " .. player.Name)\nend`
    }
  ];

  // Fetch or load snippets
  useEffect(() => {
    if (!sessionUser) {
      // Guest mode: load from localStorage
      const local = localStorage.getItem('studiohub_local_snippets');
      if (local) {
        try {
          setSnippets(JSON.parse(local));
        } catch (e) {
          console.error("Failed to parse local snippets", e);
        }
      }
      return;
    }

    setIsLoading(true);
    const q = query(
      collection(db, 'user_snippets'),
      where('userId', '==', sessionUser.uid)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const items: Snippet[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() } as Snippet);
      });
      // Sort by updatedAt descending
      items.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
      setSnippets(items);
      setIsLoading(false);
    }, (err) => {
      console.error("Firestore loading error:", err);
      setIsLoading(false);
    });

    return () => unsubscribe();
  }, [sessionUser]);

  // Insert template
  const handleLoadTemplate = (tpl: typeof templates[0]) => {
    setCode(tpl.code);
    setTitle(tpl.name);
    setDescription(tpl.desc);
    triggerToast(`Loaded template: ${tpl.name}`);
  };

  // Create new draft
  const handleCreateNew = () => {
    setSelectedSnippet(null);
    setTitle('New Luau Snippet');
    setCode('-- [[ StudioHub Luau Script ]]\n-- Write your custom Roblox scripts here\n\n');
    setDescription('');
    setTagInput('custom, client');
    setLintResult({ status: 'idle', message: '', errors: [] });
  };

  // Select snippet
  const handleSelectSnippet = (snip: Snippet) => {
    setSelectedSnippet(snip);
    setTitle(snip.title);
    setCode(snip.code);
    setDescription(snip.description || '');
    setTagInput(snip.tags ? snip.tags.join(', ') : '');
    setLintResult({ status: 'idle', message: '', errors: [] });
  };

  // Run Lint check
  const handleLintCode = () => {
    setIsLinting(true);
    setLintResult({ status: 'idle', message: '', errors: [] });

    setTimeout(() => {
      const errorsList: string[] = [];
      const lines = code.split('\n');

      // Basic Linter checks
      let openedBrackets = 0;
      let openedCurly = 0;
      let openedParens = 0;

      lines.forEach((line, index) => {
        const lineNum = index + 1;
        
        // Count matching brackets
        openedParens += (line.match(/\(/g) || []).length - (line.match(/\)/g) || []).length;
        openedCurly += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
        openedBrackets += (line.match(/\[/g) || []).length - (line.match(/\]/g) || []).length;

        // Check for common error patterns
        if (line.includes('then') && !line.includes('if') && !line.includes('elseif')) {
          errorsList.push(`Line ${lineNum}: Loose 'then' keyword without conditional statement`);
        }
        if (line.includes('end') && line.trim() === 'end' && openedCurly < 0) {
          errorsList.push(`Line ${lineNum}: Unbalanced scope closers ('end')`);
        }
      });

      if (openedParens !== 0) errorsList.push('Syntax Error: Mismatched parentheses ( ... )');
      if (openedCurly !== 0) errorsList.push('Syntax Error: Mismatched curly brackets { ... }');
      if (openedBrackets !== 0) errorsList.push('Syntax Error: Mismatched brackets [ ... ]');

      setIsLinting(false);
      if (errorsList.length === 0) {
        setLintResult({
          status: 'success',
          message: 'Valid Luau Syntax! Code compiled successfully into bytecode blocks.',
          errors: []
        });
        triggerToast("Linter checks passed successfully!");
      } else {
        setLintResult({
          status: 'error',
          message: 'Syntax warnings detected. Please verify before running.',
          errors: errorsList
        });
        triggerToast("Linter detected syntax warnings!");
      }
    }, 600);
  };

  // Save changes
  const handleSaveSnippet = async () => {
    if (!title.trim()) {
      triggerToast("Please provide a title for your snippet");
      return;
    }

    const tagsArr = tagInput
      .split(',')
      .map(t => t.trim().toLowerCase())
      .filter(t => t.length > 0);

    const snippetId = selectedSnippet?.id || 'snippet_' + Math.random().toString(36).substr(2, 9);
    const updated: Snippet = {
      id: snippetId,
      userId: sessionUser?.uid || 'guest',
      title: title.trim(),
      code,
      description: description.trim(),
      tags: tagsArr,
      createdAt: selectedSnippet?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    if (!sessionUser) {
      // Guest local storage saving
      const local = localStorage.getItem('studiohub_local_snippets');
      let currentList: Snippet[] = [];
      if (local) {
        try { currentList = JSON.parse(local); } catch (e) {}
      }
      
      const idx = currentList.findIndex(x => x.id === snippetId);
      if (idx >= 0) {
        currentList[idx] = updated;
      } else {
        currentList.unshift(updated);
      }

      localStorage.setItem('studiohub_local_snippets', JSON.stringify(currentList));
      setSnippets([...currentList]);
      setSelectedSnippet(updated);
      triggerToast("Snippet saved locally! Login to backup to Cloud.");
      return;
    }

    // Cloud saving
    try {
      await setDoc(doc(db, 'user_snippets', snippetId), updated);
      setSelectedSnippet(updated);
      triggerToast("Successfully saved snippet to Firebase Cloud!");
    } catch (err: any) {
      console.error("Save error:", err);
      triggerToast("Failed to save to cloud database");
    }
  };

  // Delete Snippet
  const handleDeleteSnippet = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm("Are you sure you want to delete this script snippet?")) return;

    if (!sessionUser) {
      const local = localStorage.getItem('studiohub_local_snippets');
      let currentList: Snippet[] = [];
      if (local) {
        try { currentList = JSON.parse(local); } catch (e) {}
      }
      const filtered = currentList.filter(x => x.id !== id);
      localStorage.setItem('studiohub_local_snippets', JSON.stringify(filtered));
      setSnippets(filtered);
      if (selectedSnippet?.id === id) {
        handleCreateNew();
      }
      triggerToast("Deleted locally");
      return;
    }

    try {
      await deleteDoc(doc(db, 'user_snippets', id));
      if (selectedSnippet?.id === id) {
        handleCreateNew();
      }
      triggerToast("Successfully deleted from Firebase Cloud");
    } catch (err) {
      triggerToast("Deletion failed");
    }
  };

  // Generate Loadstring
  const handleCopyLoadstring = () => {
    const rawUrl = `https://studiohub-loaders.pages.dev/api/snippet/${selectedSnippet?.id || 'temp'}`;
    const loadstringText = `loadstring(game:HttpGet("${rawUrl}", true))()`;
    navigator.clipboard.writeText(loadstringText);
    setCopiedLoadstring(true);
    setTimeout(() => setCopiedLoadstring(false), 2000);
    triggerToast("Injected loadstring template copied!");
  };

  const filteredSnippets = snippets.filter(s => 
    s.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    s.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
    s.tags.some(t => t.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch animate-fadeIn">
      
      {/* LEFT COLUMN - Snippet Explorer */}
      <div className="lg:col-span-4 flex flex-col gap-4">
        
        {/* Search & New draft Panel */}
        <div className={`p-4 rounded-3xl border flex flex-col gap-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <div className="flex items-center justify-between">
            <h3 className={`text-xs font-bold uppercase tracking-wider font-sans ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
              Draft explorer
            </h3>
            <button
              onClick={handleCreateNew}
              className="p-1 px-2.5 rounded-xl text-[10px] font-bold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1 cursor-pointer transition-all active:scale-95 shadow-sm"
            >
              <Plus className="w-3 h-3" /> New Snippet
            </button>
          </div>

          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
            <input
              type="text"
              placeholder="Search custom snippets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={`w-full pl-9 pr-3 py-2 text-xs rounded-xl focus:outline-none ${
                isDark 
                  ? 'bg-slate-950 border-slate-800 text-white placeholder-slate-500 focus:border-indigo-500/40' 
                  : 'bg-slate-50 border-slate-200 text-slate-800 placeholder-slate-400 focus:border-indigo-400'
              } border`}
            />
          </div>
        </div>

        {/* Snippets list wrapper */}
        <div className={`flex-1 min-h-[300px] max-h-[550px] overflow-y-auto p-4 rounded-3xl border space-y-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          {!sessionUser && (
            <div className={`p-3 rounded-2xl text-[10px] border leading-relaxed flex items-start gap-2 ${
              isDark ? 'bg-amber-500/10 border-amber-500/20 text-amber-300' : 'bg-amber-50 border-amber-200 text-amber-700'
            }`}>
              <Lock className="w-3.5 h-3.5 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Sandbox Guest Mode</p>
                <p className="opacity-80">Scripts are saved in local storage. Sign in to gain cloud backups.</p>
                <button 
                  onClick={onShowAuth}
                  className="font-bold underline text-indigo-500 hover:text-indigo-600 mt-1 cursor-pointer block"
                >
                  Sign In Now
                </button>
              </div>
            </div>
          )}

          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 text-slate-400 gap-2">
              <div className="animate-spin rounded-full h-5 w-5 border-2 border-t-indigo-500 border-r-transparent border-slate-300" />
              <span className="text-[10px] font-mono">Syncing cloud storage...</span>
            </div>
          ) : filteredSnippets.length === 0 ? (
            <div className="text-center py-16 text-slate-400 text-xs flex flex-col items-center gap-2">
              <FileCode className="w-8 h-8 opacity-40 text-slate-500" />
              <span>No custom snippets saved.</span>
            </div>
          ) : (
            filteredSnippets.map((snip) => {
              const isSelected = selectedSnippet?.id === snip.id;
              return (
                <div
                  key={snip.id}
                  onClick={() => handleSelectSnippet(snip)}
                  className={`p-3.5 rounded-2xl border text-left transition-all cursor-pointer flex flex-col gap-2 relative group overflow-hidden ${
                    isSelected
                      ? 'bg-indigo-500/5 border-indigo-500 text-zinc-900'
                      : isDark
                        ? 'bg-slate-950/40 border-slate-800/80 hover:bg-slate-800/30'
                        : 'bg-slate-50 border-slate-100 hover:bg-slate-100/50'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="truncate">
                      <h4 className={`text-xs font-bold truncate ${
                        isDark ? 'text-white' : 'text-slate-800'
                      }`}>
                        {snip.title}
                      </h4>
                      <p className="text-[10px] text-slate-400 truncate mt-0.5">
                        {snip.description || 'No description provided'}
                      </p>
                    </div>
                    <button
                      onClick={(e) => handleDeleteSnippet(snip.id, e)}
                      className="p-1 rounded-lg text-slate-400 hover:text-red-500 hover:bg-red-500/10 cursor-pointer transition-all"
                      title="Delete snippet"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <div className="flex flex-wrap gap-1 mt-1">
                    {snip.tags && snip.tags.map((tag) => (
                      <span 
                        key={tag}
                        className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-slate-500/10 text-slate-500 border border-slate-500/5"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  <div className="flex items-center justify-between text-[8px] text-slate-400 font-mono border-t border-slate-500/5 pt-1.5 mt-1">
                    <span className="flex items-center gap-1">
                      <Clock className="w-2.5 h-2.5" />
                      {new Date(snip.updatedAt).toLocaleDateString()}
                    </span>
                    <span className="flex items-center gap-1 text-[8px] text-indigo-400">
                      {snip.userId === 'guest' ? 'Local' : (
                        <span className="flex items-center gap-0.5 font-bold">
                          <Cloud className="w-2.5 h-2.5" /> Cloud
                        </span>
                      )}
                    </span>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Templates quick-load panel */}
        <div className={`p-4 rounded-3xl border space-y-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <h4 className={`text-xs font-bold flex items-center gap-1.5 uppercase tracking-wide ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
            <Sparkles className="w-4 h-4 text-indigo-500" /> Luau Templates
          </h4>
          <div className="grid grid-cols-1 gap-2">
            {templates.map((tpl) => (
              <button
                key={tpl.name}
                onClick={() => handleLoadTemplate(tpl)}
                className={`p-2.5 rounded-xl border text-left transition-all text-[10px] flex flex-col gap-0.5 cursor-pointer hover:scale-[1.01] ${
                  isDark
                    ? 'bg-slate-950/60 border-slate-800 text-slate-300 hover:bg-slate-950'
                    : 'bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100/50'
                }`}
              >
                <span className="font-bold text-slate-800 dark:text-white flex items-center gap-1.5">
                  <FileCode className="w-3.5 h-3.5 text-indigo-500" />
                  {tpl.name}
                </span>
                <span className="opacity-80 text-[9px] truncate">{tpl.desc}</span>
              </button>
            ))}
          </div>
        </div>

      </div>

      {/* RIGHT COLUMN - Luau Workspace */}
      <div className="lg:col-span-8 flex flex-col gap-6">
        
        {/* Workspace Form / Details Card */}
        <div className={`p-6 rounded-3xl border space-y-4 flex flex-col ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <div className="flex items-center justify-between border-b border-slate-500/5 pb-3">
            <div>
              <h2 className={`text-sm font-bold tracking-tight font-sans ${isDark ? 'text-white' : 'text-slate-800'}`}>
                {selectedSnippet ? 'Edit Custom Snippet' : 'Draft New Code Snippet'}
              </h2>
              <p className="text-[10px] text-slate-400">Compile and store configurations inside our simulated Luau register engine.</p>
            </div>
            
            <div className="flex items-center gap-2">
              {/* Loadstring button only if selected */}
              {selectedSnippet && (
                <button
                  onClick={handleCopyLoadstring}
                  className={`p-1.5 px-3 rounded-xl text-[10px] font-mono font-bold border transition-all flex items-center gap-1.5 cursor-pointer ${
                    copiedLoadstring
                      ? 'bg-emerald-500 border-emerald-500 text-white'
                      : 'bg-slate-100 dark:bg-slate-950 border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 hover:bg-slate-200'
                  }`}
                >
                  {copiedLoadstring ? <Check className="w-3.5 h-3.5" /> : <Clipboard className="w-3.5 h-3.5" />}
                  <span>{copiedLoadstring ? 'COPIED!' : 'GET LOADSTRING'}</span>
                </button>
              )}

              <button
                onClick={handleSaveSnippet}
                className="p-1.5 px-4 rounded-xl text-[10px] font-bold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 cursor-pointer transition-all"
              >
                <Save className="w-3.5 h-3.5" />
                <span>Save Code</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Snippet Title</label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className={`w-full px-3.5 py-2 text-xs rounded-xl focus:outline-none ${
                  isDark 
                    ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                    : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
                } border`}
              />
            </div>

            <div className="space-y-1">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Tags (comma separated)</label>
              <div className="relative">
                <Tag className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. combat, aimbot, loop"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  className={`w-full pl-9 pr-3 py-2 text-xs rounded-xl focus:outline-none ${
                    isDark 
                      ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                      : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
                  } border`}
                />
              </div>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Workspace description</label>
            <input
              type="text"
              placeholder="Write a brief note of what your custom script does"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className={`w-full px-3.5 py-2 text-xs rounded-xl focus:outline-none ${
                isDark 
                  ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                  : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
              } border`}
            />
          </div>

          {/* Actual Code Workspace Area */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 flex items-center gap-1 font-mono">
                <Code className="w-3.5 h-3.5 text-indigo-500" /> Luau Editor Workspace
              </label>
              
              <button
                onClick={handleLintCode}
                disabled={isLinting}
                className="text-[9px] font-mono font-extrabold uppercase bg-indigo-500/10 border border-indigo-500/30 text-indigo-600 px-2.5 py-1 rounded-lg hover:bg-indigo-500/20 cursor-pointer transition-all flex items-center gap-1"
              >
                {isLinting ? (
                  <>
                    <div className="animate-spin rounded-full h-2.5 w-2.5 border border-indigo-500 border-t-transparent" />
                    <span>Analyzing...</span>
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-3 h-3 text-indigo-500" />
                    <span>Lint & Validate</span>
                  </>
                )}
              </button>
            </div>

            <div className="relative rounded-2xl overflow-hidden border border-slate-800 bg-slate-950 shadow-inner flex">
              {/* Line Numbers column */}
              <div className="bg-slate-900 border-r border-slate-800 p-3 pr-2 select-none text-right font-mono text-[10px] text-slate-600 min-w-[32px] leading-relaxed hidden sm:block">
                {Array.from({ length: Math.max(12, code.split('\n').length) }).map((_, i) => (
                  <div key={i}>{i + 1}</div>
                ))}
              </div>

              {/* Textarea Code entry */}
              <textarea
                value={code}
                onChange={(e) => setCode(e.target.value)}
                className="w-full h-96 p-4 bg-transparent text-[11px] font-mono leading-relaxed text-indigo-300 focus:outline-none resize-y selection:bg-indigo-500/20"
                spellCheck="false"
                style={{ fontFamily: 'JetBrains Mono, Fira Code, Courier New, monospace' }}
              />
            </div>
          </div>

          {/* Lint result Status panel */}
          <AnimatePresence mode="wait">
            {lintResult.status !== 'idle' && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 10 }}
                className={`p-4 rounded-2xl border text-xs leading-relaxed text-left flex gap-3 ${
                  lintResult.status === 'success'
                    ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-300'
                    : 'bg-rose-500/10 border-rose-500/20 text-rose-700 dark:text-rose-300'
                }`}
              >
                {lintResult.status === 'success' ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
                ) : (
                  <AlertCircle className="w-5 h-5 text-rose-500 shrink-0" />
                )}
                
                <div className="space-y-1 flex-1">
                  <p className="font-bold">{lintResult.message}</p>
                  {lintResult.errors.length > 0 && (
                    <div className="font-mono text-[10px] space-y-1 bg-black/20 p-2.5 rounded-lg border border-white/5 mt-2">
                      {lintResult.errors.map((err, i) => (
                        <p key={i} className="text-rose-400">✗ {err}</p>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>

    </div>
  );
}
