import React, { useState, useEffect } from 'react';
import { 
  Code, Save, Play, Clipboard, Check, Trash2, Plus, Search, 
  Sparkles, CheckCircle2, AlertCircle, FileCode, Tag, Clock, Cloud, Lock,
  Terminal, Cpu, Loader2, X, Sliders, RefreshCw, Layers, Wifi, Activity, Info, Tv, Target
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { db } from '../firebase';
import { 
  collection, query, where, getDocs, doc, setDoc, deleteDoc, 
  serverTimestamp, onSnapshot, updateDoc 
} from 'firebase/firestore';
import { ForestSimulator } from './ForestSimulator';

interface Snippet {
  id: string;
  userId: string;
  title: string;
  code: string;
  description: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

interface ScriptSandboxProps {
  sessionUser: { uid: string; displayName: string; photoURL: string; email: string } | null;
  theme: 'studio-light' | 'studio-dark' | 'neon' | 'ultradark';
  triggerToast: (msg: string) => void;
  onShowAuth: () => void;
  preloadedCode?: string;
  onClearPreloadedCode?: () => void;
}

export function ScriptSandbox({ sessionUser, theme, triggerToast, onShowAuth, preloadedCode, onClearPreloadedCode }: ScriptSandboxProps) {
  const [snippets, setSnippets] = useState<Snippet[]>([]);
  const [selectedSnippet, setSelectedSnippet] = useState<Snippet | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  // Form states for the current workspace
  const [title, setTitle] = useState('New Luau Snippet');
  const [code, setCode] = useState('-- [[ StudioHub Luau Learning Script ]]\n-- Write safe Roblox Studio learning snippets here\n\nlocal function greet()\n    print("Hello from a local learning snippet!")\nend\n\ngreet()');
  const [description, setDescription] = useState('My educational Luau snippet');
  const [tagInput, setTagInput] = useState('learning, ui');

  // Linter & compilation simulator states
  const [lintResult, setLintResult] = useState<{
    status: 'idle' | 'success' | 'error';
    message: string;
    errors: string[];
  }>({ status: 'idle', message: '', errors: [] });
  const [isLinting, setIsLinting] = useState(false);
  const [copiedLoadstring, setCopiedLoadstring] = useState(false);

  // Local learning simulation states inside sandbox
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionLogs, setExecutionLogs] = useState<string[]>([]);
  const [executionStep, setExecutionStep] = useState(0);
  const [simulatedWalkSpeed, setSimulatedWalkSpeed] = useState(120);
  const [simulatedFly, setSimulatedFly] = useState(false);
  const [simulatedNoclip, setSimulatedNoclip] = useState(false);
  const [simulatedEsp, setSimulatedEsp] = useState(true);
  const [detectedGameId, setDetectedGameId] = useState<'nights_forest' | 'generic'>('generic');

  const isDark = theme === 'studio-dark' || theme === 'ultradark' || theme === 'neon';

  // Listen to incoming preloaded code
  useEffect(() => {
    if (preloadedCode) {
      setCode(preloadedCode);
      setTitle('Imported AI Template');
      setDescription('Luau script generated by Sentinel-1 Support Assistant');
      if (onClearPreloadedCode) {
        onClearPreloadedCode();
      }
      triggerToast('AI Script outline loaded successfully! Click Run to compile.');
    }
  }, [preloadedCode, onClearPreloadedCode, triggerToast]);

  // Code Templates list
  const templates = [
    {
      name: 'UI Button Demo',
      desc: 'Creates a simple clickable UI button',
      code: `-- [[ SAFE UI BUTTON DEMO ]]\nlocal screenGui = Instance.new("ScreenGui")\nscreenGui.Name = "LearningButtonDemo"\n\nlocal button = Instance.new("TextButton")\nbutton.Size = UDim2.new(0, 180, 0, 44)\nbutton.Text = "Click Me"\nbutton.Parent = screenGui\n\nbutton.MouseButton1Click:Connect(function()\n    print("Button clicked in a local learning demo")\nend)\n\nprint("Parent screenGui to PlayerGui when testing in Roblox Studio.")`
    },
    {
      name: 'Debounced Event Demo',
      desc: 'Shows how to debounce repeated input safely',
      code: `-- [[ DEBOUNCED EVENT DEMO ]]\nlocal busy = false\n\nlocal function handleAction()\n    if busy then return end\n    busy = true\n    print("Action accepted once, then debounced briefly.")\n    task.wait(0.5)\n    busy = false\nend\n\nhandleAction()\nhandleAction()`
    },
    {
      name: 'Table Filter Demo',
      desc: 'Filters a list of tagged values',
      code: `-- [[ TABLE FILTER DEMO ]]\nlocal items = {\n    { name = "Campfire", tag = "landmark" },\n    { name = "Pine Tree", tag = "resource" },\n    { name = "Cabin", tag = "landmark" }\n}\n\nfor _, item in ipairs(items) do\n    if item.tag == "landmark" then\n        print("Landmark:", item.name)\n    end\nend`
    }
  ];

  // Fetch or load snippets
  useEffect(() => {
    if (!sessionUser) {
      // Guest mode: load from localStorage
      const local = localStorage.getItem('studiohub_local_snippets');
      if (local) {
        try {
          setSnippets(JSON.parse(local));
        } catch (e) {
          console.error("Failed to parse local snippets", e);
        }
      }
      return;
    }

    setIsLoading(true);
    const q = query(
      collection(db, 'user_snippets'),
      where('userId', '==', sessionUser.uid)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const items: Snippet[] = [];
      snapshot.forEach((doc) => {
        items.push({ id: doc.id, ...doc.data() } as Snippet);
      });
      // Sort by updatedAt descending
      items.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
      setSnippets(items);
      setIsLoading(false);
    }, (err) => {
      console.error("Firestore loading error:", err);
      setIsLoading(false);
    });

    return () => unsubscribe();
  }, [sessionUser]);

  // Insert template
  const handleLoadTemplate = (tpl: typeof templates[0]) => {
    setCode(tpl.code);
    setTitle(tpl.name);
    setDescription(tpl.desc);
    triggerToast(`Loaded template: ${tpl.name}`);
  };

  // Create new draft
  const handleCreateNew = () => {
    setSelectedSnippet(null);
    setTitle('New Luau Snippet');
    setCode('-- [[ StudioHub Luau Script ]]\n-- Write your custom Roblox scripts here\n\n');
    setDescription('');
    setTagInput('custom, client');
    setLintResult({ status: 'idle', message: '', errors: [] });
  };

  // Select snippet
  const handleSelectSnippet = (snip: Snippet) => {
    setSelectedSnippet(snip);
    setTitle(snip.title);
    setCode(snip.code);
    setDescription(snip.description || '');
    setTagInput(snip.tags ? snip.tags.join(', ') : '');
    setLintResult({ status: 'idle', message: '', errors: [] });
  };

  // Run Lint check
  const handleLintCode = () => {
    setIsLinting(true);
    setLintResult({ status: 'idle', message: '', errors: [] });

    setTimeout(() => {
      const errorsList: string[] = [];
      const lines = code.split('\n');

      // Basic Linter checks
      let openedBrackets = 0;
      let openedCurly = 0;
      let openedParens = 0;

      lines.forEach((line, index) => {
        const lineNum = index + 1;
        
        // Count matching brackets
        openedParens += (line.match(/\(/g) || []).length - (line.match(/\)/g) || []).length;
        openedCurly += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
        openedBrackets += (line.match(/\[/g) || []).length - (line.match(/\]/g) || []).length;

        // Check for common error patterns
        if (line.includes('then') && !line.includes('if') && !line.includes('elseif')) {
          errorsList.push(`Line ${lineNum}: Loose 'then' keyword without conditional statement`);
        }
        if (line.includes('end') && line.trim() === 'end' && openedCurly < 0) {
          errorsList.push(`Line ${lineNum}: Unbalanced scope closers ('end')`);
        }
      });

      if (openedParens !== 0) errorsList.push('Syntax Error: Mismatched parentheses ( ... )');
      if (openedCurly !== 0) errorsList.push('Syntax Error: Mismatched curly brackets { ... }');
      if (openedBrackets !== 0) errorsList.push('Syntax Error: Mismatched brackets [ ... ]');

      setIsLinting(false);
      if (errorsList.length === 0) {
        setLintResult({
          status: 'success',
          message: 'Valid Luau-style syntax check passed for this educational preview.',
          errors: []
        });
        triggerToast("Linter checks passed successfully!");
      } else {
        setLintResult({
          status: 'error',
          message: 'Syntax warnings detected. Please verify before running.',
          errors: errorsList
        });
        triggerToast("Linter detected syntax warnings!");
      }
    }, 600);
  };

  // Save changes
  const handleSaveSnippet = async () => {
    if (!title.trim()) {
      triggerToast("Please provide a title for your snippet");
      return;
    }

    const tagsArr = tagInput
      .split(',')
      .map(t => t.trim().toLowerCase())
      .filter(t => t.length > 0);

    const snippetId = selectedSnippet?.id || 'snippet_' + Math.random().toString(36).substr(2, 9);
    const updated: Snippet = {
      id: snippetId,
      userId: sessionUser?.uid || 'guest',
      title: title.trim(),
      code,
      description: description.trim(),
      tags: tagsArr,
      createdAt: selectedSnippet?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    if (!sessionUser) {
      // Guest local storage saving
      const local = localStorage.getItem('studiohub_local_snippets');
      let currentList: Snippet[] = [];
      if (local) {
        try { currentList = JSON.parse(local); } catch (e) {}
      }
      
      const idx = currentList.findIndex(x => x.id === snippetId);
      if (idx >= 0) {
        currentList[idx] = updated;
      } else {
        currentList.unshift(updated);
      }

      localStorage.setItem('studiohub_local_snippets', JSON.stringify(currentList));
      setSnippets([...currentList]);
      setSelectedSnippet(updated);
      triggerToast("Snippet saved locally! Login to backup to Cloud.");
      return;
    }

    // Cloud saving
    try {
      await setDoc(doc(db, 'user_snippets', snippetId), updated);
      setSelectedSnippet(updated);
      triggerToast("Successfully saved snippet to Firebase Cloud!");
    } catch (err: any) {
      console.error("Save error:", err);
      triggerToast("Failed to save to cloud database");
    }
  };

  // Delete Snippet
  const handleDeleteSnippet = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm("Are you sure you want to delete this script snippet?")) return;

    if (!sessionUser) {
      const local = localStorage.getItem('studiohub_local_snippets');
      let currentList: Snippet[] = [];
      if (local) {
        try { currentList = JSON.parse(local); } catch (e) {}
      }
      const filtered = currentList.filter(x => x.id !== id);
      localStorage.setItem('studiohub_local_snippets', JSON.stringify(filtered));
      setSnippets(filtered);
      if (selectedSnippet?.id === id) {
        handleCreateNew();
      }
      triggerToast("Deleted locally");
      return;
    }

    try {
      await deleteDoc(doc(db, 'user_snippets', id));
      if (selectedSnippet?.id === id) {
        handleCreateNew();
      }
      triggerToast("Successfully deleted from Firebase Cloud");
    } catch (err) {
      triggerToast("Deletion failed");
    }
  };

  // Generate Loadstring
  const handleCopyLoadstring = () => {
    const rawUrl = `https://studiohub-loaders.pages.dev/api/snippet/${selectedSnippet?.id || 'temp'}`;
    // Educational source reference for review; avoid executing untrusted remote code
    const sourceReference = `-- Educational source reference only\n-- Review this URL before using any code:\n-- ${rawUrl}`;
    navigator.clipboard.writeText(sourceReference);
    setCopiedLoadstring(true);
    setTimeout(() => setCopiedLoadstring(false), 2000);
    triggerToast("Educational source reference copied!");
  };

  const startSandboxLearningSimulation = () => {
    setIsExecuting(true);
    setExecutionStep(0);
    setExecutionLogs([]);
    
    const lowCode = code.toLowerCase();
    const isForestScript = lowCode.includes('nightsintheforest') || lowCode.includes('nights_forest') || lowCode.includes('nights in the forest');
    setDetectedGameId(isForestScript ? 'nights_forest' : 'generic');

    const baseLogs = [
      '🔧 [Sandbox] Initializing local learning preview...',
      '🔍 [Sandbox] Checking draft text...',
      '📌 [Sandbox] Connected draft to preview state.',
      '🛡️ [Safety] Confirmed no bypass hooks or telemetry capture are included.',
      '🌐 [GitHub Linker] Verifying active master connection with raw.githubusercontent.com...',
      '✅ [GitHub Linker] Connection verified! Git HEAD secure and connected (Repo: ZeroHub-Roblox/scripts)',
    ];

    const logs = [...baseLogs];

    // Try to extract a URL to mock fetching it
    const urlMatch = code.match(/https?:\/\/[^\s"'()]+/);
    if (urlMatch) {
      const detectedUrl = urlMatch[0];
      logs.push(`📡 [Source Preview] Preparing educational reference metadata...`);
      logs.push(`📦 [Source Preview] Referencing source URL: "${detectedUrl.substring(0, 48)}..."`);
      logs.push(`✅ [Source Preview] Metadata prepared without executing remote code.`);
    } else {
      logs.push(`📝 [Parser] Loading custom pasted Luau source code buffers...`);
      logs.push(`⚡ [Formatter] Parsing text for local preview display...`);
    }

    logs.push('🚀 [Sandbox] Local preview simulation completed.');
    logs.push('✨ [ZeroHub] Educational sandbox preview is ready.');

    let currentLog = 0;
    const logTimer = setInterval(() => {
      if (currentLog < logs.length) {
        setExecutionLogs(prev => [...prev, logs[currentLog]]);
        setExecutionStep(currentLog + 1);
        currentLog++;
      } else {
        clearInterval(logTimer);
      }
    }, 280);
  };

  const filteredSnippets = snippets.filter(s => 
    s.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    s.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
    s.tags.some(t => t.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch animate-fadeIn">
      
      {/* LEFT COLUMN - Snippet Explorer */}
      <div className="lg:col-span-4 flex flex-col gap-4">
        
        {/* Search & New draft Panel */}
        <div className={`p-4 rounded-3xl border flex flex-col gap-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <div className="flex items-center justify-between">
            <h3 className={`text-xs font-bold uppercase tracking-wider font-sans ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
              Draft explorer
            </h3>
            <button
              onClick={handleCreateNew}
              className="p-1 px-2.5 rounded-xl text-[10px] font-bold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1 cursor-pointer transition-all active:scale-95 shadow-sm"
            >
              <Plus className="w-3 h-3" /> New Snippet
            </button>
          </div>

          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
            <input
              type="text"
              placeholder="Search custom snippets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={`w-full pl-9 pr-3 py-2 text-xs rounded-xl focus:outline-none ${
                isDark 
                  ? 'bg-slate-950 border-slate-800 text-white placeholder-slate-500 focus:border-indigo-500/40' 
                  : 'bg-slate-50 border-slate-200 text-slate-800 placeholder-slate-400 focus:border-indigo-400'
              } border`}
            />
          </div>
        </div>

        {/* GitHub Connection Badge */}
        <div className={`p-4 rounded-3xl border flex items-center justify-between transition-all select-none ${
          isDark ? 'bg-emerald-500/5 border-emerald-500/20 text-emerald-400' : 'bg-emerald-50 border-emerald-100 text-emerald-700'
        }`}>
          <div className="flex items-center gap-2.5">
            <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse shadow-[0_0_8px_rgba(52,211,153,0.5)]" />
            <div className="text-left">
              <p className="text-[10px] font-mono font-extrabold uppercase leading-none">GitHub Repo Status</p>
              <p className="text-[8px] opacity-70 font-mono mt-1">ZeroHub-Roblox/scripts (Synced)</p>
            </div>
          </div>
          <span className="text-[9px] font-mono font-extrabold uppercase bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-0.5 rounded-full">
            Connected
          </span>
        </div>

        {/* Snippets list wrapper */}
        <div className={`flex-1 min-h-[300px] max-h-[550px] overflow-y-auto p-4 rounded-3xl border space-y-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          {!sessionUser && (
            <div className={`p-3 rounded-2xl text-[10px] border leading-relaxed flex items-start gap-2 ${
              isDark ? 'bg-amber-500/10 border-amber-500/20 text-amber-300' : 'bg-amber-50 border-amber-200 text-amber-700'
            }`}>
              <Lock className="w-3.5 h-3.5 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Sandbox Guest Mode</p>
                <p className="opacity-80">Scripts are saved in local storage. Sign in to gain cloud backups.</p>
                <button 
                  onClick={onShowAuth}
                  className="font-bold underline text-indigo-500 hover:text-indigo-600 mt-1 cursor-pointer block"
                >
                  Sign In Now
                </button>
              </div>
            </div>
          )}

          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 text-slate-400 gap-2">
              <div className="animate-spin rounded-full h-5 w-5 border-2 border-t-indigo-500 border-r-transparent border-slate-300" />
              <span className="text-[10px] font-mono">Syncing cloud storage...</span>
            </div>
          ) : filteredSnippets.length === 0 ? (
            <div className="text-center py-16 text-slate-400 text-xs flex flex-col items-center gap-2">
              <FileCode className="w-8 h-8 opacity-40 text-slate-500" />
              <span>No custom snippets saved.</span>
            </div>
          ) : (
            filteredSnippets.map((snip) => {
              const isSelected = selectedSnippet?.id === snip.id;
              return (
                <div
                  key={snip.id}
                  onClick={() => handleSelectSnippet(snip)}
                  className={`p-3.5 rounded-2xl border text-left transition-all cursor-pointer flex flex-col gap-2 relative group overflow-hidden ${
                    isSelected
                      ? 'bg-indigo-500/5 border-indigo-500 text-zinc-900'
                      : isDark
                        ? 'bg-slate-950/40 border-slate-800/80 hover:bg-slate-800/30'
                        : 'bg-slate-50 border-slate-100 hover:bg-slate-100/50'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="truncate">
                      <h4 className={`text-xs font-bold truncate ${
                        isDark ? 'text-white' : 'text-slate-800'
                      }`}>
                        {snip.title}
                      </h4>
                      <p className="text-[10px] text-slate-400 truncate mt-0.5">
                        {snip.description || 'No description provided'}
                      </p>
                    </div>
                    <button
                      onClick={(e) => handleDeleteSnippet(snip.id, e)}
                      className="p-1 rounded-lg text-slate-400 hover:text-red-500 hover:bg-red-500/10 cursor-pointer transition-all"
                      title="Delete snippet"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <div className="flex flex-wrap gap-1 mt-1">
                    {snip.tags && snip.tags.map((tag) => (
                      <span 
                        key={tag}
                        className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-slate-500/10 text-slate-500 border border-slate-500/5"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  <div className="flex items-center justify-between text-[8px] text-slate-400 font-mono border-t border-slate-500/5 pt-1.5 mt-1">
                    <span className="flex items-center gap-1">
                      <Clock className="w-2.5 h-2.5" />
                      {new Date(snip.updatedAt).toLocaleDateString()}
                    </span>
                    <span className="flex items-center gap-1 text-[8px] text-indigo-400">
                      {snip.userId === 'guest' ? 'Local' : (
                        <span className="flex items-center gap-0.5 font-bold">
                          <Cloud className="w-2.5 h-2.5" /> Cloud
                        </span>
                      )}
                    </span>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Templates quick-load panel */}
        <div className={`p-4 rounded-3xl border space-y-3 ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <h4 className={`text-xs font-bold flex items-center gap-1.5 uppercase tracking-wide ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
            <Sparkles className="w-4 h-4 text-indigo-500" /> Luau Templates
          </h4>
          <div className="grid grid-cols-1 gap-2">
            {templates.map((tpl) => (
              <button
                key={tpl.name}
                onClick={() => handleLoadTemplate(tpl)}
                className={`p-2.5 rounded-xl border text-left transition-all text-[10px] flex flex-col gap-0.5 cursor-pointer hover:scale-[1.01] ${
                  isDark
                    ? 'bg-slate-950/60 border-slate-800 text-slate-300 hover:bg-slate-950'
                    : 'bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100/50'
                }`}
              >
                <span className="font-bold text-slate-800 dark:text-white flex items-center gap-1.5">
                  <FileCode className="w-3.5 h-3.5 text-indigo-500" />
                  {tpl.name}
                </span>
                <span className="opacity-80 text-[9px] truncate">{tpl.desc}</span>
              </button>
            ))}
          </div>
        </div>

      </div>

      {/* RIGHT COLUMN - Luau Workspace */}
      <div className="lg:col-span-8 flex flex-col gap-6">
        
        {/* Workspace Form / Details Card */}
        <div className={`p-6 rounded-3xl border space-y-4 flex flex-col ${
          isDark ? 'bg-slate-900/60 border-slate-800' : 'bg-white border-slate-200/80 shadow-sm'
        }`}>
          <div className="flex items-center justify-between border-b border-slate-500/5 pb-3">
            <div>
              <h2 className={`text-sm font-bold tracking-tight font-sans ${isDark ? 'text-white' : 'text-slate-800'}`}>
                {selectedSnippet ? 'Edit Custom Snippet' : 'Draft New Code Snippet'}
              </h2>
              <p className="text-[10px] text-slate-400">Check, preview, and store educational Luau snippets.</p>
            </div>
            
            <div className="flex items-center gap-2">
              {/* Run in learning simulation button */}
              <button
                onClick={startSandboxLearningSimulation}
                className="p-1.5 px-3 rounded-xl text-[10px] font-mono font-extrabold bg-amber-500 hover:bg-amber-400 text-black flex items-center gap-1.5 cursor-pointer transition-all active:scale-95 shadow-md shadow-amber-500/10"
                title="Preview draft in local educational simulator"
              >
                <Play className="w-3.5 h-3.5 fill-black text-black" />
                <span>RUN PREVIEW</span>
              </button>

              {/* Loadstring button only if selected */}
              {selectedSnippet && (
                <button
                  onClick={handleCopyLoadstring}
                  className={`p-1.5 px-3 rounded-xl text-[10px] font-mono font-bold border transition-all flex items-center gap-1.5 cursor-pointer ${
                    copiedLoadstring
                      ? 'bg-emerald-500 border-emerald-500 text-white'
                      : 'bg-slate-100 dark:bg-slate-950 border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 hover:bg-slate-200'
                  }`}
                >
                  {copiedLoadstring ? <Check className="w-3.5 h-3.5" /> : <Clipboard className="w-3.5 h-3.5" />}
                  <span>{copiedLoadstring ? 'COPIED!' : 'GET LOADSTRING'}</span>
                </button>
              )}

              <button
                onClick={handleSaveSnippet}
                className="p-1.5 px-4 rounded-xl text-[10px] font-bold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 cursor-pointer transition-all"
              >
                <Save className="w-3.5 h-3.5" />
                <span>Save Code</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Snippet Title</label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className={`w-full px-3.5 py-2 text-xs rounded-xl focus:outline-none ${
                  isDark 
                    ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                    : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
                } border`}
              />
            </div>

            <div className="space-y-1">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Tags (comma separated)</label>
              <div className="relative">
                <Tag className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. combat, aimbot, loop"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  className={`w-full pl-9 pr-3 py-2 text-xs rounded-xl focus:outline-none ${
                    isDark 
                      ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                      : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
                  } border`}
                />
              </div>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 block font-mono">Workspace description</label>
            <input
              type="text"
              placeholder="Write a brief note of what your custom script does"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className={`w-full px-3.5 py-2 text-xs rounded-xl focus:outline-none ${
                isDark 
                  ? 'bg-slate-950 border-slate-800 text-white focus:border-indigo-500/30' 
                  : 'bg-slate-50 border-slate-200 text-slate-800 focus:border-indigo-400'
              } border`}
            />
          </div>

          {/* Actual Code Workspace Area */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="text-[9px] uppercase tracking-wider font-bold text-slate-400 flex items-center gap-1 font-mono">
                <Code className="w-3.5 h-3.5 text-indigo-500" /> Luau Editor Workspace
              </label>
              
              <button
                onClick={handleLintCode}
                disabled={isLinting}
                className="text-[9px] font-mono font-extrabold uppercase bg-indigo-500/10 border border-indigo-500/30 text-indigo-600 px-2.5 py-1 rounded-lg hover:bg-indigo-500/20 cursor-pointer transition-all flex items-center gap-1"
              >
                {isLinting ? (
                  <>
                    <div className="animate-spin rounded-full h-2.5 w-2.5 border border-indigo-500 border-t-transparent" />
                    <span>Analyzing...</span>
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-3 h-3 text-indigo-500" />
                    <span>Lint & Validate</span>
                  </>
                )}
              </button>
            </div>

            <div className="relative rounded-2xl overflow-hidden border border-slate-800 bg-slate-950 shadow-inner flex">
              {/* Line Numbers column */}
              <div className="bg-slate-900 border-r border-slate-800 p-3 pr-2 select-none text-right font-mono text-[10px] text-slate-600 min-w-[32px] leading-relaxed hidden sm:block">
                {Array.from({ length: Math.max(12, code.split('\n').length) }).map((_, i) => (
                  <div key={i}>{i + 1}</div>
                ))}
              </div>

              {/* Textarea Code entry */}
              <textarea
                value={code}
                onChange={(e) => setCode(e.target.value)}
                className="w-full h-96 p-4 bg-transparent text-[11px] font-mono leading-relaxed text-indigo-300 focus:outline-none resize-y selection:bg-indigo-500/20"
                spellCheck="false"
                style={{ fontFamily: 'JetBrains Mono, Fira Code, Courier New, monospace' }}
              />
            </div>
          </div>

          {/* Lint result Status panel */}
          <AnimatePresence mode="wait">
            {lintResult.status !== 'idle' && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 10 }}
                className={`p-4 rounded-2xl border text-xs leading-relaxed text-left flex gap-3 ${
                  lintResult.status === 'success'
                    ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-700 dark:text-emerald-300'
                    : 'bg-rose-500/10 border-rose-500/20 text-rose-700 dark:text-rose-300'
                }`}
              >
                {lintResult.status === 'success' ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
                ) : (
                  <AlertCircle className="w-5 h-5 text-rose-500 shrink-0" />
                )}
                
                <div className="space-y-1 flex-1">
                  <p className="font-bold">{lintResult.message}</p>
                  {lintResult.errors.length > 0 && (
                    <div className="font-mono text-[10px] space-y-1 bg-black/20 p-2.5 rounded-lg border border-white/5 mt-2">
                      {lintResult.errors.map((err, i) => (
                        <p key={i} className="text-rose-400">✗ {err}</p>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

      </div>

      {/* LEARNING SANDBOX SIMULATOR OVERLAY MODAL */}
      <AnimatePresence>
        {isExecuting && (
          <div className="fixed inset-0 bg-black/85 backdrop-blur-md flex items-center justify-center p-4 z-50 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="w-full max-w-2xl bg-zinc-950 border border-amber-500/30 rounded-3xl overflow-hidden shadow-[0_0_50px_rgba(245,158,11,0.15)] flex flex-col my-8"
            >
              {/* Modal Header */}
              <div className="bg-zinc-900 border-b border-white/5 px-6 py-4 flex items-center justify-between text-xs font-mono font-bold text-zinc-400">
                <div className="flex items-center gap-2.5">
                  <Cpu className="w-4 h-4 text-amber-400 animate-pulse" />
                  <span>ZEROHUB SANDBOX v4.5</span>
                  <span className="text-[9px] px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-full font-bold uppercase tracking-widest animate-pulse">PREVIEW READY</span>
                </div>
                <button
                  onClick={() => setIsExecuting(false)}
                  className="p-1.5 rounded-xl bg-white/5 hover:bg-rose-500/20 hover:text-rose-400 transition-all cursor-pointer border border-transparent hover:border-rose-500/20"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Console Logs/Viewport Area */}
              <div className="p-6 space-y-4 font-mono text-[11px] min-h-[300px] flex-1 flex flex-col justify-between">
                
                {/* Simulated Steps log terminal */}
                <div className="space-y-2 max-h-[180px] overflow-y-auto text-left text-zinc-300 pr-1 scrollbar-thin">
                  {executionLogs.map((log, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: -5 }}
                      animate={{ opacity: 1, x: 0 }}
                      className={`leading-relaxed ${
                        log.includes('SUCCESS') || log.includes('✅') ? 'text-emerald-400 font-extrabold' :
                        log.includes('Welcome') || log.includes('✨') ? 'text-cyan-400 font-extrabold' : 
                        log.includes('🔧') || log.includes('🔍') ? 'text-amber-400' : 'text-zinc-300'
                      }`}
                    >
                      {log}
                    </motion.div>
                  ))}
                  {executionStep < 8 && (
                    <div className="flex items-center gap-2 text-amber-400/80 animate-pulse mt-2">
                      <Loader2 className="w-3.5 h-3.5 animate-spin text-amber-400" />
                      <span>Processing payload modules...</span>
                    </div>
                  )}
                </div>

                {/* Loading / Bytecode Processing Bar */}
                {executionStep < 8 && (
                  <div className="space-y-2 mt-4">
                    <div className="flex justify-between text-[10px] text-zinc-500">
                      <span>Analyzing memory blocks and preloading scripts...</span>
                      <span>{Math.round((executionStep / 8) * 100)}%</span>
                    </div>
                    <div className="w-full bg-zinc-900 h-2 rounded-full overflow-hidden border border-white/5">
                      <div
                        className="bg-amber-400 h-full transition-all duration-300 shadow-[0_0_8px_rgba(245,158,11,0.5)]"
                        style={{ width: `${(executionStep / 8) * 100}%` }}
                      />
                    </div>
                  </div>
                )}

                {/* If step reaches maximum, display appropriate GUI HUD */}
                {executionStep >= 8 && (
                  detectedGameId === 'nights_forest' ? (
                    <motion.div 
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-4 text-left border-t border-white/5 pt-4 w-full"
                    >
                      <ForestSimulator
                        walkSpeed={simulatedWalkSpeed}
                        jumpPower={120}
                        extraToggles={{
                          autoWood: true,
                          autoAura: true,
                          antiRagdoll: true,
                          noclip: simulatedNoclip,
                          infiniteFly: simulatedFly
                        }}
                        extraSliders={{
                          yieldTarget: 80,
                          auraDistance: 25
                        }}
                        onClose={() => setIsExecuting(false)}
                      />
                    </motion.div>
                  ) : (
                    <motion.div
                      initial={{ opacity: 0, y: 15, scale: 0.98 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      className="mt-4 bg-gradient-to-b from-zinc-900 to-black border border-cyan-500/40 rounded-2xl p-5 shadow-[0_0_30px_rgba(6,182,212,0.15)] relative overflow-hidden"
                    >
                      <div className="absolute inset-0 bg-grid-pattern opacity-5 pointer-events-none" />

                      {/* HUD Header */}
                      <div className="flex items-center justify-between border-b border-white/5 pb-3 mb-4 relative z-10">
                        <div className="flex items-center gap-2">
                          <Tv className="w-5 h-5 text-cyan-400 animate-bounce" />
                          <div>
                            <span className="text-xs font-black tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-300 uppercase">
                              ZeroHub Roblox HUD
                            </span>
                            <p className="text-[8px] text-zinc-500 font-mono leading-none mt-0.5">Active Executor Hook: Custom Sandbox Script</p>
                          </div>
                        </div>
                        <span className="text-[9px] font-mono px-2 py-0.5 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 font-bold uppercase tracking-widest animate-pulse">
                          Active Bypass
                        </span>
                      </div>

                      {/* HUD Features Slider / Toggles */}
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 relative z-10 text-left">
                        {/* Speed Alterer */}
                        <div className="space-y-2 bg-white/2 p-3 rounded-xl border border-white/5">
                          <div className="flex items-center justify-between text-[10px]">
                            <span className="text-zinc-400 font-bold">👟 Movement Preview Value</span>
                            <span className="text-cyan-400 font-mono font-bold">{simulatedWalkSpeed} / 250</span>
                          </div>
                          <input
                            type="range"
                            min="16"
                            max="250"
                            value={simulatedWalkSpeed}
                            onChange={(e) => setSimulatedWalkSpeed(Number(e.target.value))}
                            className="w-full h-1 bg-black rounded-lg appearance-none cursor-pointer accent-cyan-500"
                          />
                        </div>

                        {/* Sliders / Toggles Column */}
                        <div className="space-y-2 text-[10px]">
                          <button
                            onClick={() => setSimulatedFly(!simulatedFly)}
                            className={`w-full p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer font-bold ${
                              simulatedFly
                                ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-[0_0_10px_rgba(16,185,129,0.05)]'
                                : 'bg-black/30 border-white/5 text-zinc-500 hover:text-zinc-300'
                            }`}
                          >
                            <span className="flex items-center gap-1.5">🛸 Debounced Event Demo Fly</span>
                            <span>{simulatedFly ? 'ON' : 'OFF'}</span>
                          </button>

                          <button
                            onClick={() => setSimulatedNoclip(!simulatedNoclip)}
                            className={`w-full p-2.5 rounded-xl border flex items-center justify-between transition-all cursor-pointer font-bold ${
                              simulatedNoclip
                                ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-[0_0_10px_rgba(16,185,129,0.05)]'
                                : 'bg-black/30 border-white/5 text-zinc-500 hover:text-zinc-300'
                            }`}
                          >
                            <span className="flex items-center gap-1.5">🌀 Noclip (Pass Walls)</span>
                            <span>{simulatedNoclip ? 'ON' : 'OFF'}</span>
                          </button>
                        </div>
                      </div>

                      {/* HUD Footer status metrics */}
                      <div className="mt-4 pt-3 border-t border-white/5 flex items-center justify-between text-[9px] text-zinc-500">
                        <div className="flex items-center gap-1.5">
                          <Activity className="w-3.5 h-3.5 text-emerald-400 animate-pulse" />
                          <span>Status: In-game HUD fully responsive</span>
                        </div>
                        <button
                          onClick={() => setIsExecuting(false)}
                          className="px-3 py-1 rounded-xl bg-white/5 hover:bg-white/15 text-[9px] text-white transition-all font-mono uppercase font-bold cursor-pointer border border-white/5"
                        >
                          Return to Code Workspace
                        </button>
                      </div>
                    </motion.div>
                  )
                )}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
